name: ${project.name}
main: com.aeonicdev.xephyr.plugin.XephyrPlugin
version: ${project.version}
description: ${project.description}
authors: [maladr0it, hauno]
load: startup
softdepend: [WorldEdit, WorldGuard]